### ISSUE TITLE
Event FlagChanged doesn't trigger on creation a new flag

### ISSUE THREAD

**Issue by tomertr** [launchdarkly/dotnet-client-sdk#31]
The event FlagChanged doesn't trigger on creation of a new flag, it only triggers on changes made to flags that already existed during the last query to AllFlags.

**To reproduce**
Register to the LdClient event FlagChanged then add a new flag to LaunchDarkly

**Expected behavior**
The event should be triggered on the new flag added

**SDK version**
Xamarin 1.2.0.0

**OS/platform**
Windows 10

**Comment by eli-darkly** [comment]
Thanks for reporting this. I see where the flaw in the logic is, and it's pretty straightforward, so putting out a fix will only depend on our overall project/release pipeline which is a little backed up at the moment. I'll file it as low-hanging fruit to be addressed as soon as there's a chance.

**Comment by eli-darkly** [comment]
Sorry for the lack of an update on this issue before. This behavior is fixed in the new 2.0.0 release, as part of its somewhat different flag change event API (basically, instead of `LdClient.FlagChanged` it is now `LdClient.FlagTracker.FlagValueChanged` and the name of the argument type has changed). We probably won't put out a 1.x patch.
