### ISSUE TITLE
do we have a release date for LaunchDarkly.ClientSdk?

### ISSUE THREAD

**Issue by theboyknowsclass** [launchdarkly/dotnet-client-sdk#34]
at the moment all i can see is Alpha versions?

**Comment by eli-darkly** [comment]
Hi - thanks for your interest. We've been fine-tuning this release for a while, since it's a major rewrite with a fair amount of new functionality. We're just about ready to put out a release _candidate_, 2.0.0-rc.1, which we expect to be either identical to or very close to what will be in 2.0.0. That's likely to be either today or early next week, and it'll be accompanied by a migration guide explaining the differences from 1.x.

Once that is out, we're going to wait a couple of weeks to give interested developers a chance to play with it and see if they turn up any issues we haven't thought of. If there are no further changes required after that, we'll do the 2.0.0 GA release. We'll also update the main documentation page at that point to refer to the new version.

**Comment by eli-darkly** [comment]
Also, just to give you an idea of the overall plan: there is some additional work we have in mind after 2.0.0, such as the ability to configure the SDK to use more than one LaunchDarkly environment (a feature that already exists in our native Android and iOS SDKs). We don't have a time frame for that yet, but we didn't want to hold up the 2.0.0 release for it, and it shouldn't involve any backward-incompatible changes so it can be a minor version release.

The other big task for this SDK will be to start using the new mobile runtime frameworks that are part of .NET 6.0, which are intended to replace `xamarin-android` and `xamarin-ios`. That is still pretty new, so we expect that current developers will still be using the older frameworks for a while, and we'll continue to maintain the 2.x SDK as long as it's within the scope of our [end of life policy](https://launchdarkly.com/policies/end-of-life-policy/). We would expect to migrate to the new frameworks in a 3.0 release of the SDK (or later, if we need to introduce some other new functionality that might require a backward-incompatible API change, in which case that would be 3.0 and the framework change would be 4.0).

**Comment by eli-darkly** [comment]
We've published 2.0.0-rc.1. However, there was a holdup in publishing the new documentation, so you may get "not found" if you click the migration guide link in the release notes. That should be fixed shortly.

**Comment by eli-darkly** [comment]
OK, here's the prerelease: https://github.com/launchdarkly/dotnet-client-sdk/releases/tag/2.0.0-rc.1

**Comment by theboyknowsclass** [comment]
Thanks, FYI, I've ported our previous solution to this with no issues - though initialisation time seems slower - though I haven't benchmarked if as yet

**Comment by eli-darkly** [comment]
> initialisation time seems slower

Hmm - can't think of any reason that that should be. Can you tell me what platform you're running on? Also, do you know if that's the length of time between calling `LdClient.Init` and having it successfully start (which might indicate that the slowness involves I/O), or does the delay start when you first call some code in the SDK such as `Configuration.Builder` (which might indicate that it's taking time to load the assembly, before anything executes)?

**Comment by eli-darkly** [comment]
The 2.0.0 GA release is now live! Sorry for the delays.
