### ISSUE TITLE
Nested segments do not evaluate correctly 

### ISSUE THREAD

**Issue by burns47** [launchdarkly/dotnet-client-sdk#94]
**Describe the bug**

LaunchDarkly does not correctly evaluate targeting rules involving segments that reference another segment.  

**To reproduce**
Create a segment:
![image](https://github.com/launchdarkly/dotnet-client-sdk/assets/24252293/e335be04-bb5c-4b8d-b91c-0ae4e7a40d97)

Then create another segment that references that segment:
![image](https://github.com/launchdarkly/dotnet-client-sdk/assets/24252293/283aae51-4d6c-4858-b6f4-f11e799e3ab5)

Create a LD rule that targets the outer segment:
![image](https://github.com/launchdarkly/dotnet-client-sdk/assets/24252293/2135fda0-527d-4abd-84f2-22caa6e71aea)

**Expected behavior**
`false` would be served if my email was `jake.burns@dutchie.com`.

The rule fails and reports that the fallthrough rule was used:

![image](https://github.com/launchdarkly/dotnet-client-sdk/assets/24252293/e183ce0a-ea3c-474c-af13-66a0fcb27a38)

If I instead target the inner segment directly:

![image](https://github.com/launchdarkly/dotnet-client-sdk/assets/24252293/efead150-5028-4e9b-a44e-e36209f853b7)

Then the flag evaluates as expected:
![image](https://github.com/launchdarkly/dotnet-client-sdk/assets/24252293/3748f664-d636-4fe0-a918-d31e8c0cdbc3)

**Logs**
If applicable, add any log output related to your problem.

**SDK version**
6.3.1

**Language version, developer tools**
.NET 6

**OS/platform**
Windows & Ubuntu

**Additional context**

**Comment by kinyoklion** [comment]
Hello @burns47,

This is the repository for the client-side SDK. Your intent seems to be the server SDK, as the version number correlates with a server SDK.

In order to use nested segments you need version 7.0 or higher of the server sdk. Contexts and nested segment support were added in that version.

This is the server repository: https://github.com/launchdarkly/dotnet-server-sdk

Please note that 6.x is beyond its EOL.

Thank you,
Ryan

**Comment by burns47** [comment]
Thank you @kinyoklion - I was unaware of the difference, my apologies.  I'll close this issue!
